### ISSUE TITLE
Integration of bin2cell Pipeline with cell2location Workflow

### ISSUE THREAD

**Issue by lisch7** [Teichlab/bin2cell#20]
Hello bin2cell Team,

Firstly, I want to extend my deepest appreciation for your remarkable work on the bin2cell tool. It has provided crucial insights and has been extremely useful in my analysis of spatial transcriptomics data.

As someone relatively new to this field, I am eager to integrate the cell segmentation outputs from bin2cell with the cell2location workflow in HD data. Having completed the segmentation using bin2cell, I find myself unsure about the best practices for merging these results with cell2location. Could you provide any recommended approaches or guidelines that might help in smoothly transitioning the outputs from bin2cell to the inputs for cell2location?

Any advice or suggestions you could offer on this integration would be immensely appreciated.

Thank you for your time and dedication to developing such an invaluable tool.

Best regards

**Comment by nadavyayon** [comment]
Hi,

Thanks for your message. This is not related to bin2cell itself but still since you asked ill briefly reply. 

For cell type inference we show the use of CellTypist in our demo notebooks as it's assumptions are that you are working with single cells. Cell2location assumes a mixture of cells and derives the relative abundance for all query cells per spot. 

Both these approaches can be debated and are highly dependent on cell density in my opinion. 

Beyond that we can't really provide recommendations on how to run Cell2location or any other downstream tools for that matter. 

Good luck on your quest!

**Comment by lisch7** [comment]
Thank you for your prompt and kind reply!
