### ISSUE TITLE
When do I need to shift?

### ISSUE THREAD

**Issue by inofechm** [Teichlab/bin2cell#37]
Hi Bin2Cell developers.
I've had a lot of fun experimenting with the package, but was wondering if you can provide some advice on when I should apply a shift. 

For example in the attached picture (before any shift) do I even need to apply a transformation, to me it looks decent but if I look at some regions such as a bottom left it looks like if could benefit from a shift to the right but the small group of cells beside that look like they could benefit from a shift to the left.

As such I am a bit lost in how to decide the shift...

Any advice would be appreciated.
Thanks,
Ido
![eg_IF](https://github.com/user-attachments/assets/1c76d51e-a0f9-4b80-a584-032676a44be6)

**Comment by nadavyayon** [comment]
Hi Ido,

We recommend to perform manual alignment with loupe browser if you witness an issue.  Ideally you should never need to introduce an xy shift manually. 

It is generally also very difficult to say if there is a shift unless it's something drastic. 

But in your case, since the tissue has many gaps and free cells. I would load the raw object without filtering tissue spots.  This might better highlight if you have an alignment issues. 

Hope that helps 

Nadav

**Comment by inofechm** [comment]
Cheers this is helpful!
Thanks!
