### ISSUE TITLE
OpenCV error with b2c.scaled_he_image using cytassist_image.tiff

### ISSUE THREAD

**Issue by cmiciano** [Teichlab/bin2cell#5]
Hello, thanks for creating such a useful tool! 

I'm following the demo notebook, and I'm trying to run` b2c.scaled_he_image(adata, mpp=mpp, save_path="stardist_nash/he.tiff")` with a value of 0.5 for mpp but I'm getting the error

`error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'`

My input to `source_image_path` is the `cytassist_image.tiff` in the `spatial` folder of my Space Ranger output folder. 

How can I fix this error? Also is it possible to try using the `tissue_hires_image.png` from the same folder as input to `source_image_path`?
<img width="1045" alt="Screenshot 2024-08-21 at 4 58 44 PM" src="https://github.com/user-attachments/assets/3c212bae-9493-41c0-a4bb-20431327a842">

**Comment by ktpolanski** [comment]
Use the high resolution (the actual high resolution one you used as spaceranger input, not `tissue_hires_image.png`) tissue image rather than the CytAssist one.

You're not the first person to bump into this, a coworker did this locally, and also saw this error. Maybe there's a check that can be done and result in a more informative error.

**Comment by cmiciano** [comment]
Hello, thank you so much for your prompt response, that makes sense. I’ve managed to segment out the cells but will probably try different parameters for mpp, nms_thresh and prob_thresh to make it clearer. 


<img width="979" alt="Screenshot 2024-08-21 at 11 54 52 PM" src="https://github.com/user-attachments/assets/990ac62f-3f24-47a8-9514-ca475043c22e">

Another question, the demo notebook shows how to do the segmentation for a small region of the image, but how would you go about running bin2cell on the whole image? In your notebook N2_demo_analysis_mouse_brain_submission.ipynb you have an AnnData object m_brain_b2c.h5ad that I assume is the object where the segmented cell x gene counts matrix is generated. 

Would I remove the lines that create the mask and subset the adata object by the mask? I’m also curious as to how much memory it requires to run bin2cell on the whole image.

**Comment by nadavyayon** [comment]
Hey!

bin2cell segments the entire image, but plotting 2um bins (adata) is very heavy so we demonstrate the results on a small cropped object throughout the pipeline (bdata). 

Once the final cell object (cdata) is generated you can plot the entire image using the same scanpy plotting functions. This can also be quite slow depending on the numbers of cells you get. 

Judging from the image you shared your nuclei are very small so I would definitely recommend using a lower (higher resolution) mpp such as 0.25. 

Hope this helps

**Comment by cmiciano** [comment]
Oh I see, thank you for clarifying that the cdata object contains all of the segmented cells. Thanks for the suggestion, I'll try an mpp of 0.25.

**Comment by ktpolanski** [comment]
I'm not sure what exactly you're referring to as "having this error" if you can't load the image.

From what I'm seeing, tiffile supports the format, and `b2c.scaled_if_image()` uses tiffile internally. As such, there's a chance that you'll be able to use that function if there's a particular channel that is to be imported. If not, experiment with tiffile syntax.

I think that rather than support corner cases like that, I might add an extra argument to the functions for optionally passing a pre-loaded image for cropping/scaling.

**Comment by lpantano** [comment]
Thank you, I will try then. I am having this error:

```
error: OpenCV(4.10.0) /io/opencv/modules/imgproc/src/resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

mentioned as well here: #6 . And I think that is because I don't have the right image as well. Thanks!

**Comment by ktpolanski** [comment]
Oh, I see. I wondered why you replied here, now I see. In that case, let's do standard diagnostics for this:
1. What's the file name you're specifying for `source_image_path` at the time of `b2c.read_visium()`?
2. What happens if you try to just `b2c.load_image()` said file? What is the `.shape` of the returned array?

**Comment by lpantano** [comment]
Thank you, right now I am using an image that is `*Scan.qptiff` until I can have the TIFF image, this image is around 300Mb, any other image I have is around 22MB and they are CytAssist images. 

This is the shape of the img and below is the adata array, I don't know if those number should match, they are close but not the same so maybe I really need to push for getting the exact image giving to space ranger. Thanks in advance!

```
img = b2c.load_image("....Scan2.qptiff")
img.shape
(79200, 28800, 3)
```

```
np.min(adata.obsm["spatial"],axis=0)
np.max(adata.obsm["spatial"],axis=0)
array([16277.05461548, 74886.6011456 ])
```

**Comment by nadavyayon** [comment]
Hi, just to mention you can only work with the image that was used for spaceranger mapping or at least one that was converted to a different format from it. Any deviation from the original pixel size would probably misalign your image and transcriptomics grid. This misalignment will make bin2cell segmentations irrelevant.
